Raspimouse:
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50
  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: 'wheel_r_joint'
    right_wheel: 'wheel_l_joint'
    #    pid: {p: 100.0, i: 0.01, d: 10.0} 
    wheel_radius: 0.024
    wheel_separation : 0.08
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    cmd_vel_timeout: 20.0 #we test this spearately, give plenty for the other test
